mysql-server-9.7: follow refactor TIME handring
Ref: mysql/mysql-server@6b5b6f5

Use Item::val_time() instead of Item::get_time() since MySQL 9.7.
Field::get_time() is removed in MySQL 9.7.

The following error is resolved by this modification.

```
/root/rpmbuild/BUILD/mroonga-16.08/ha_mroonga.cpp: In member function 'int ha_mroonga::generic_store_bulk_time(Field*, grn_obj*)':
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: error: 'class Field_time' has no member named 'get_time'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: note: in definition of macro 'MRN_FIELD_GET_TIME'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/ha_mroonga.cpp: In member function 'int ha_mroonga::generic_store_bulk_datetime(Field*, grn_obj*)':
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: error: 'class Field_datetime' has no member named 'get_time'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: note: in definition of macro 'MRN_FIELD_GET_TIME'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/ha_mroonga.cpp: In member function 'int ha_mroonga::generic_store_bulk_datetime2(Field*, grn_obj*)':
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: error: 'using mrn_field_datetime = class Field_datetime' {aka 'class Field_datetime'} has no member named 'get_time'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: note: in definition of macro 'MRN_FIELD_GET_TIME'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/ha_mroonga.cpp: In member function 'int ha_mroonga::generic_store_bulk_time2(Field*, grn_obj*)':
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: error: 'class Field' has no member named 'get_time'; did you mean 'get_image'?
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: note: in definition of macro 'MRN_FIELD_GET_TIME'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/ha_mroonga.cpp: In member function 'int ha_mroonga::generic_store_bulk_new_date(Field*, grn_obj*)':
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: error: 'class Field_date' has no member named 'get_time'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
/root/rpmbuild/BUILD/mroonga-16.08/mrn_mysql_compat.h:802:58: note: in definition of macro 'MRN_FIELD_GET_TIME'
  802 | #  define MRN_FIELD_GET_TIME(field, time, thd) ((field)->get_time((time)))
      |                                                          ^~~~~~~~
```